import numpy as np

from reservoir_market_backtest.model import (
    IkedaConfiguration,
    ikeda_states,
    scores_to_up_values,
    walk_forward_ridge_scores,
)


def small_configuration(seed: int = 1234) -> IkedaConfiguration:
    return IkedaConfiguration(
        virtual_nodes=4,
        theta_steps=2,
        dt=0.05,
        feedback_gain_beta=0.3,
        phase_offset=0.8,
        input_scale=0.02,
        auxiliary_delta=0.0,
        desynchronization=1,
        mask_seed=seed,
    )


def test_ikeda_reconstruction_is_deterministic_and_stateful() -> None:
    features = np.arange(36, dtype=float).reshape(12, 3) / 36.0
    first = ikeda_states(features, small_configuration())
    second = ikeda_states(features, small_configuration())
    changed_seed = ikeda_states(features, small_configuration(seed=7))
    assert first.shape == (12, 4)
    np.testing.assert_array_equal(first, second)
    assert not np.array_equal(first, changed_seed)
    assert not np.array_equal(first[0], first[-1])


def test_ikeda_python_loop_matches_frozen_native_kernel_fixture() -> None:
    """Values were generated by the hash-recorded historical C kernel."""

    features = np.arange(36, dtype=float).reshape(12, 3) / 36.0
    states = ikeda_states(features, small_configuration())
    np.testing.assert_allclose(
        states[0],
        [
            0.10535076976410641,
            0.11014735552986284,
            0.11441129988398953,
            0.1182919978276429,
        ],
        rtol=0.0,
        atol=5e-15,
    )
    np.testing.assert_allclose(
        states[-1],
        [
            0.2090159542248589,
            0.20906698926762943,
            0.20805113915744403,
            0.20815128620012863,
        ],
        rtol=0.0,
        atol=5e-15,
    )


def test_walk_forward_predictions_do_not_use_future_targets() -> None:
    rng = np.random.default_rng(4)
    states = rng.normal(size=(40, 5))
    targets = np.sign(rng.normal(size=40))
    changed = targets.copy()
    changed[25:] *= -1
    first, mask = walk_forward_ridge_scores(
        states,
        targets,
        initial_training_days=10,
        retrain_every=5,
        embargo=2,
    )
    second, second_mask = walk_forward_ridge_scores(
        states,
        changed,
        initial_training_days=10,
        retrain_every=5,
        embargo=2,
    )
    np.testing.assert_array_equal(mask, second_mask)
    np.testing.assert_allclose(first[10:25], second[10:25])
    assert np.isnan(first[:10]).all()
    assert mask[10:].all()


def test_historical_score_transform_threshold() -> None:
    values = scores_to_up_values(np.array([-1.0, 0.0, 1.0]))
    assert values[0] < 0.5
    assert values[1] == 0.5
    assert values[2] > 0.5
